/*********************************************************************
 *
 *                 ZCL Scenes Cluster Header File
 *
 *********************************************************************
 * FileName:        ZCL_Scenes.h
 * Dependencies:
 * Processor:       PIC18 / PIC24 / PIC32
 * Complier:        MCC18 v3.00 or higher
 *                  MCC30 v2.05 or higher
 *                  MCC32 v2.05 or higher
 * Company:         Microchip Technology, Inc.
 *
 * Software License Agreement
 *
 * Copyright © 2004-2007 Microchip Technology Inc.  All rights reserved.
 *
 * Microchip licenses to you the right to use, copy and distribute Software
 * only when embedded on a Microchip microcontroller or digital signal
 * controller and used with a Microchip radio frequency transceiver, which
 * are integrated into your product or third party product (pursuant to the
 * sublicense terms in the accompanying license agreement).  You may NOT
 * modify or create derivative works of the Software.
 *
 * If you intend to use this Software in the development of a product for
 * sale, you must be a member of the ZigBee Alliance.  For more information,
 * go to www.zigbee.org.
 *
 * You should refer to the license agreement accompanying this Software for
 * additional information regarding your rights and obligations.
 *
 * SOFTWARE AND DOCUMENTATION ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY
 * KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY
 * OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR
 * PURPOSE. IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR OBLIGATED
 * UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION, BREACH OF
 * WARRANTY, OR OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT DAMAGES OR
 * EXPENSES INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL, INDIRECT,
 * PUNITIVE OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA, COST OF
 * PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY CLAIMS BY
 * THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF), OR OTHER
 * SIMILAR COSTS.
 *
 * Author               Date            Comment
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *                      03/23/09
 *****************************************************************************/
#ifndef _ZCL_SCENES_H
#define _ZCL_SCENES_H
/****************************************************************************
   Includes
 *****************************************************************************/
/* None */

/*****************************************************************************
  Constants and Enumerations
 *****************************************************************************/
/*Scenes cluster Identifier as defined by ZCL specification*/
#define ZCL_SCENES_CLUSTER                0x0005

/*Scenes Cluster Attribute Set*/
#define ZCL_SCENES_SCENE_COUNT						0x0000
#define ZCL_SCENES_CURRENT_SCENE					0x0001
#define ZCL_SCENES_CURRENT_GROUP					0x0002
#define ZCL_SCENES_SCENE_VALID						0x0003
#define ZCL_SCENES_NAME_SUPPORT_ATTRIBUTE			0x0004
#if (I_SUPPORT_OPTIONAL_ZCL_ATTRIBUTES == 0x01 )
	#define ZCL_SCENES_LAST_CONFIGURED_BY			0x0005
#endif /*I_SUPPORT_OPTIONAL_ZCL_ATTRIBUTES*/

/*This indicates the position of ZCL payload in Scenes command.*/
#define ZCL_SCENES_CMD_PAYLOAD_POSITION        	0x03

/*Events handled by the application*/
enum Scenes_Cluster_Events
{
    ZCL_Scenes_AddSceneEvent              	   	= 0xB0,
    ZCL_Scenes_ViewSceneEvent                  	= 0xB1,
	ZCL_Scenes_RemoveSceneEvent					= 0xB2,
	ZCL_Scenes_RemoveAllScenesEvent				= 0xB3,
	ZCL_Scenes_StoreSceneEvent					= 0xB4,
	ZCL_Scenes_RecallSceneEvent					= 0xB5,
    ZCL_Scenes_GetSceneMembershipEvent       	= 0xB6,  
    ZCL_Scenes_AddSceneResponseEvent            = 0xB7,
    ZCL_Scenes_ViewSceneResponseEvent          	= 0xB8,
	ZCL_Scenes_RemoveSceneResponseEvent			= 0xB9,
	ZCL_Scenes_RemoveAllScenesResponseEvent		= 0xBA,
	ZCL_Scenes_StoreSceneResponseEvent			= 0xBB,
    ZCL_Scenes_GetSceneMembershipResponseEvent  = 0xBC 
};

/*Commands generated by Client Side of the ScenesCluster*/
enum Scenes_Generated_Commands
{
    ZCL_Scenes_AddSceneCmd              	   	= 0x00,
    ZCL_Scenes_ViewSceneCmd                  	= 0x01,
    ZCL_Scenes_RemoveSceneCmd       			= 0x02,
	ZCL_Scenes_RemoveAllScenesCmd				= 0x03,
	ZCL_Scenes_StoreSceneCmd					= 0x04,
	ZCL_Scenes_RecallSceneCmd					= 0x05,
    ZCL_Scenes_GetSceneMembershipCmd       		= 0x06  
};
/*Commands Received by Client Side of the ScenesCluster*/
enum Scenes_Received_Commands
{
    ZCL_Scenes_AddSceneResponseCmd            	= 0x00,
    ZCL_Scenes_ViewSceneResponseCmd          	= 0x01,
	ZCL_Scenes_RemoveSceneResponseCmd			= 0x02,
	ZCL_Scenes_RemoveAllScenesResponseCmd		= 0x03,
	ZCL_Scenes_StoreSceneResponseCmd			= 0x04,
    ZCL_Scenes_GetSceneMembershipResponseCmd  	= 0x06 
};

/*****************************************************************************
 Customizable Macros
 *****************************************************************************/
 /* None */

 /*****************************************************************************
   Variable definitions
 *****************************************************************************/
  /* None */

/*****************************************************************************
                            Data Structures
 *****************************************************************************/
/*Stucture for Scenes Cluster's Attributes*/
typedef struct __attribute__((packed,aligned(1))) _ZCL_ScenesClusterAttributes
{
	BYTE sceneCount;
	BYTE currentScene;
	WORD currentGroup;
	BYTE sceneValid;
	BYTE nameSupport;
#if (I_SUPPORT_OPTIONAL_ZCL_ATTRIBUTES == 0x01 )
	BYTE lastConfiguredBy[8];
#endif /*I_SUPPORT_OPTIONAL_ZCL_ATTRIBUTES*/	
}ZCL_ScenesClusterAttributes;

typedef struct __attribute__((packed,aligned(1))) _ZCL_Scenes_AddSceneCmdPayload
{
    WORD groupId;
    BYTE sceneId;
    WORD transitionTime;
	BYTE sceneName[16];
	BYTE extFieldSets[1];
}ZCL_Scenes_AddSceneCmdPayload;

typedef struct __attribute__((packed,aligned(1))) _ZCL_Scenes_ViewSceneCmdPayload
{
    WORD groupId;
    BYTE sceneId;
}ZCL_Scenes_ViewSceneCmdPayload;

typedef struct __attribute__((packed,aligned(1))) _ZCL_Scenes_RemoveSceneCmdPayload
{
    WORD groupId;
    BYTE sceneId;
}ZCL_Scenes_RemoveSceneCmdPayload;

typedef struct __attribute__((packed,aligned(1))) _ZCL_Scenes_RemoveAllScenesCmdPayload
{
    WORD groupId;
}ZCL_Scenes_RemoveAllScenesCmdPayload;

typedef struct __attribute__((packed,aligned(1))) _ZCL_Scenes_StoreSceneCmdPayload
{
    WORD groupId;
    BYTE sceneId;
}ZCL_Scenes_StoreSceneCmdPayload;

typedef struct __attribute__((packed,aligned(1))) _ZCL_Scenes_RecallSceneCmdPayload
{
    WORD groupId;
    BYTE sceneId;
}ZCL_Scenes_RecallSceneCmdPayload;

typedef struct __attribute__((packed,aligned(1))) _ZCL_Scenes_GetSceneMembershipCmdPayload
{
    WORD groupId;
}ZCL_Scenes_GetSceneMembershipCmdPayload;


/*****************************************************************************
   Variable definitions
 *****************************************************************************/
extern ROM ZCL_ClusterDefinition zcl_ScenesClusterServerDefinition;
extern ROM ZCL_ClusterDefinition zcl_ScenesClusterClientDefinition;

extern ROM ZCL_ClusterInfo zcl_ScenesClusterServerInfo;
extern ROM ZCL_ClusterInfo zcl_ScenesClusterClientInfo;

/*****************************************************************************
  Function Prototypes
 *****************************************************************************/

/******************************************************************************
 * Function:        BYTE ZCL_HandleScenesClusterCommand
 *                  (
 *                      BYTE endPointId,
 *                      BYTE asduLength,
 *                      BYTE* pReceivedAsdu,
 *                      BYTE* pResponseAsduStartLocation,
 *                      ZCL_ActionHandler* pActionHandler,
 *                      ROM ZCL_ClusterInfo* pZCLClusterInfo
 *                  );
 *
 * PreCondition:    None
 *
 * Input:           endPointId  - EndPoint on which the ScenesCluster command
 *                                 needs to be processed.
 *                  asduLength - Asdu Length of the recevied frame.
 *                  pReceivedAsdu - This point to the actual data received.
 *                                  This consists of ZCL header and Payload.
 *                  pZCLClusterInfo - Pointer pointing to the ScenesClusterinfo
 *
 * Output:          pResponseAsduStartLocation - Pointer pointing to the start
 *                                               location of asdu for which the
 *                                               response frame needs to be
 *                                               created
*                  pActionHandler -  This is used to notify the application
*                                    that a response frame is generated or not.
*                                    It also holds the information of the type
*                                    event to be handled by the application
*                                    and  has the  payload of the recevied
*                                    data.
 * Return :         Returns the length of the response frame created
 * Side Effects:    None
 *
 * Overview:        This function is called when a Scenes Cluster command
 *                  is received.
 *                  This function process the Scenes Cluster commands and
 *                  notifies the application about the action to be taken.
 * Note:            None
 *****************************************************************************/
BYTE ZCL_HandleScenesClusterCommand
(
    BYTE endPointId,
    BYTE asduLength,
    BYTE* pReceivedAsdu,
    BYTE* pResponseAsduStartLocation,
    ZCL_ActionHandler *pActionHandler,
    ROM ZCL_ClusterInfo *pZCLClusterInfo
);

/******************************************************************************
 *	Function:   	BYTE ZCL_Callback_HandleSceneCmds
 *					(
 *    					BYTE endPointId,
 *    					BYTE* pReceivedAsdu,
 *   					BYTE* pResponsePayloadStartLocation
 *					)
 *
 * PreCondition:    None
 *
 * Input:           endPointId  - EndPoint on which the Scenes Cluster command needs
 *                                 to be processed.
 *                  pReceivedAsdu - This point to the actual data received.
 *                                  This consists of ZCL header and Payload.
 *                  pZCLClusterInfo - Pointer pointing to the Scenes Cluster info
 *
 * Output:          pResponseAsduStartLocation - Pointer pointing to the start
 *                                               location of asdu payload for which the
 *                                               response payload needs to be created
 * Return :         Returns the length of the payload of response frame created
 * Side Effects:    None
 *
 * Overview:        This function is called when a Scenes Cluster command
 *                  is received with client to srever direction.
 *                  This function process the Scenes Cluster commands and 
 *                  builds the rseponse payload if required .
 *****************************************************************************/
BYTE ZCL_Callback_HandleSceneCmds
(
    BYTE endPointId,
	BYTE asduLength,
    BYTE* pReceivedAsdu,
    BYTE* pResponsePayloadStartLocation
);

#endif      /*_ZCL_SCENES_H*/
